### PR TITLE
fix(handlers): refactor and write end-to-end tests for the create lease handler

### LINKED ISSUE #19: Write end-to-end handler tests for CreateLease
As of now, code coverage in #16 in the `./handlers/...` package is at 33.3% of statements and writing end-to-end handler tests will greatly increase it. `TestCreateLeaseValidResp` should be re-enabled (and fixed)

### PR DESCRIPTION
**Pull request by arschles**
Fixes #19 

The refactor is to make it easier to write tests for smaller portions of the handler.

This PR now brings the `handlers` package to 70.5% coverage:

``` console
ok      github.com/deis/k8s-claimer/handlers    0.019s  coverage: 70.5% of statements
```

### CODE REVIEW

File: handlers/create_lease.go [hunk 1]
```diff
@@ -68,33 +66,39 @@ func CreateLease(
...
-		}
-		if expiredLeaseErr == nil {
-			cl, ok := clusterMap.ClusterByName(uuidAndLease.Lease.ClusterName)
-			if !ok {
-				htp.Error(w, http.StatusInternalServerError, "cluster %s has an expired lease but does not exist in GKE", uuidAndLease.Lease.ClusterName)
+		availableCluster, err := searchForFreeCluster(clusterMap, leaseMap)
+		if err != nil {
+			switch e := err.(type) {
+			case errNoAvailableOrExpiredClustersFound:
+				htp.Error(w, http.StatusConflict, "no available clusters found")
```
Comment (vdice) [inline handlers/create_lease.go:73]: In this and the below error case, can't we use the error message provided by the correlating err struct itself?  Or, in other words, should we be somehow utilizing `err.Error()` here?

**Comment by vdice** [comment]
Added a note around error messaging but otherwise code LGTM

File: handlers/create_lease.go (hunk 1 above)
Comment (arschles) [inline handlers/create_lease.go:73]: @vdice since this represents the barrier between the server & client, I wanted to hard-code something here. we could put the error text in parentheses, but in both cases here it says pretty much the same thing. anyway, would you prefer it?

Comment (vdice) [inline handlers/create_lease.go:73]: @arschles gotcha. No strong opinion on the matter for me -- sounds good!
